const Products = [
    {
        id: 1,
        img: './products/apple-watch.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 2,
        img: './products/dell-XPS-13-Black.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 3,
        img: './products/dell-XPS-13-White.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 4,
        img: './products/dell-XPS-15-Black.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 5,
        img: './products/headphones.png',
        title: 'Sony ZX33OBT',
        type: 'Series 5 SE',
        price: 39.99,
        count: 1,
    },
    {
        id: 6,
        img: './products/iphone-12-01.png',
        title: 'Iphone 12',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 7,
        img: './products/iphone-12-02.png',
        title: 'Iphone 12',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 8,
        img: './products/iphone-12-03.png',
        title: 'Iphone 12',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 9,
        img: './products/iphone-12-Pro-01.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
    {
        id: 10,
        img: './products/iphone-12-Pro-02.png',
        title: 'Apple Watch',
        type: 'Series 5 SE',
        price: 529.99,
        count: 1,
    },
]
export default Products